### ISSUE TITLE
Order of magnitute difference in atmospheric pressure

### ISSUE THREAD

**Issue by sandromehic** [NickCrews/ms5803py#1]
Hi, thanks for converting the arduino library to python code!

I installed the library on a raspberry with MS5803 connected and tried the example code. The code is working (aside the small bug with a missing colon on line 5 `while True`), but it is returning a pressure number that is an order of magnitude lower than what it's supposed to be.

The sensor is connected to breadboard, so at atmospheric pressure that should be around 1013 mBar in this moment at my location. Example output:

```
pressure=100.171758 mBar, temp=27.418654 C
pressure=100.282485 mBar, temp=27.383891 C
pressure=100.167856 mBar, temp=27.383891 C
pressure=100.163954 mBar, temp=27.349128 C
pressure=100.276620 mBar, temp=27.331746 C
```

Is this a bug of just a missing 0 to some multiplication, or is the sensor not reading the data correctly, or something else entirely? Have you updated and tweaked this library but have not updated github yet? 

Thanks again!

**Comment by jdcast** [comment]
After comparing example values in various stages of the conversion math from `Figure 15` in the [datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5803-14BA%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5803-14BA_B3.pdf%7FCAT-BLPS0013) to printouts in `sensor.py`, I think it's just a simple bug on line [79](https://github.com/NickCrews/ms5803py/blob/master/ms5803py/sensor.py#L79): divide by `10` instead of a `100`.

**Comment by sandromehic** [comment]
Just checked with other libraries (arduino) and the typical values from datasheet, and the division should be by `10` not `100`. This is a simple fix, so if required I can create a quick PR, or whoever is the current maintainer can directly commit and push it, so if anybody else comes across this library it works as intended.

Again, thanks for porting this from arduino to python, saved me some hours of work :+1:

**Comment by NickCrews** [comment]
Hi! Wow, I'm glad that someone finds this useful 😄

I'll fix the division error and the example.

I copied the math from ControlEverythingCommunity version, so they have the same division error: https://github.com/ControlEverythingCommunity/MS5803-14BA/blob/master/Python/MS5803_14BA.py#L91 Want to make an issue there so their code is correct too? Probably should have been able to guess something was wrong when the earth's atmospheric pressure was 10x less than it should be 🤦‍♂

**Comment by NickCrews** [comment]
Fixed in 0d94c9a32d1b8f3e8b46ec120dc1420dfb40923f. Thanks!

**Comment by sandromehic** [comment]
Perfect, thanks for the update!

**Comment by NickCrews** [comment]
FYI, now that I know others are using this, I've been refactoring this and adding more of the features the MS5803 supports. I found [an error in the pressure correction where OFF2 should be found by dividing by 2, not by 8](https://github.com/NickCrews/ms5803py/blob/master/ms5803py/sensor.py#L70). I will fix this in an upcoming commit.

**Comment by sandromehic** [comment]
Looking forward to testing the new version then! Thanks again!
